name: Build Solution

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'

    - name: Restore .NET dependencies
      run: dotnet restore Bambi5_Launcher/Collei_Launcher.csproj

    - name: Build .NET project
      run: dotnet build Bambi5_Launcher/Collei_Launcher.csproj --configuration Release

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore C++ dependencies
      run: msbuild /t:restore /p:Configuration=Release MetadataConverter_Dll/MetadataConverter.vcxproj

    - name: Build C++ project
      run: msbuild MetadataConverter_Dll/MetadataConverter.vcxproj /p:Configuration=Release
